variants:
- name: default
  context:
    label: Button
- name: disabled
  context:
    label: Disabled button
    disabled: true
- name: with-image
  context:
    image: /assets/images/icons/addToCart.png
    label: Button with image
    mods: [with-image]
- name: more
  context:
    label: Show me another 24 waysâ€¦
    href: ?page=2
    mods: [more]
- name: secondary
  context:
    label: Button with background secondary
    mods: [secondary]
- name: dark
  context:
    label: Button dark
    mods: [dark]
- name: dark-custom
  context:
    label: Button dark with separately custom class
    mods: [dark]
    customClassList: myCustomClass1 topLeveleComponent__btn
- name: secondary-big
  context:
    label: Button with background secondary and BIG
    mods: [secondary, big]
